LEDHSV: LEDHSV Class Reference
LEDHSV Class Reference
#include <LEDHSV.h>
Public Member Functions
LEDHSV ()
LEDHSV (const LEDHSV &pLEDHSV)
LEDHSV (int pRedPin, int pGreenPin, int pBluePin, float pHue, float pSaturation, float pBrightness, bool pAutoSend, bool pAnode)
LEDHSV (int pRedPin, int pGreenPin, int pBluePin, bool pAutoSend=false, bool pAnode=false)
~LEDHSV ()
void setHue (float pHue, bool sendAfter=true)
void setSaturation (float pSaturation, bool sendAfter=true)
void setBrightness (float pBrightness, bool sendAfter=true)
void setAutoSend (bool pAutoSend)
int getRedPin ()
int getGreenPin ()
int getBluePin ()
int getRedValue ()
int getGreenValue ()
int getBlueValue ()
float getHue ()
float getSaturation ()
float getBrightness ()
bool getAutoSend ()
bool getState ()
bool getAnode ()
void off ()
void on ()
virtual void send ()
void setHSV (float pHue, float pSaturation, float pBrightness)
LEDHSV & operator= (const LEDHSV &pLEDHSV)
bool operator== (const LEDHSV &pLEDHSV) const
bool operator!= (const LEDHSV &pLEDHSV) const
Protected Member Functions
void init (int pRedPin, int pGreenPin, int pBluePin, float pHue, float pSaturation, float pBrightness, bool pAutoSend, bool pAnode)
void setup ()
void HSV2RGB ()
void setRGB (int pRedValue, int pGreenValue, int pBlueValue)
void setPins (int pRedPin, int pGreenPin, int pBluePin)
void setState (bool pState)
void setAnode (bool pAnode)
void setRedPin (int pRedPin)
void setGreenPin (int pGreenPin)
void setBluePin (int pBluePin)
void setRedValue (int pRedValue)
void setGreenValue (int pGreenValue)
void setBlueValue (int pBlueValue)
Protected Attributes
int redPin
int greenPin
int bluePin
int redValue
int greenValue
int blueValue
float hue
float saturation
float brightness
bool autoSend
bool state
bool anode
Detailed Description
Represents a physical LED and allows you to control it via HSV color space
Author
Jesse R. Castro
Version
I%, G%
Definition at line 16 of file LEDHSV.h.
Constructor & Destructor Documentation
LEDHSV::LEDHSV ()
Default class constructor for initializing with no values.
Author
Jesse R. Castro
Definition at line 7 of file LEDHSV.cpp.
References init().
LEDHSV::LEDHSV (const LEDHSV & pLEDHSV)
Copy class constructor for initializing with another instance of this class.
Author
Jesse R. Castro
Parameters
pLEDHSV An instance of the same type as this object.
Definition at line 10 of file LEDHSV.cpp.
LEDHSV::LEDHSV (int pRedPin, int pGreenPin, int pBluePin, float pHue, float pSaturation, float pBrightness, bool pAutoSend, bool pAnode)
Class constructor for initializing with individual parameters.
Author
Jesse R. Castro
Parameters
pRedPin An int value with the address of the red leg of the LED.
pGreenPin An int value with the address of the green leg of the LED.
pBluePin An int value with the address of the blue leg of the LED.
pHue A float value representing the color of the LED.
pSaturation A float value representing the Saturation of the color of the LED.
pBrightness A float value representing the brightness of the LED.
pAutoSend A boolean value representing whether to automatically send the RGB values to the physical LED when private method setRGB is called.
pAnode A boolean value representing whether the LED is common anode or cathode
Definition at line 13 of file LEDHSV.cpp.
References init().
LEDHSV::LEDHSV (int pRedPin, int pGreenPin, int pBluePin, bool pAutoSend = false, bool pAnode = false)
Class constructor for initializing with only pins and optionally the autoSend and anode flags (useful if you just want to initialize and setup without any color info).
Author
Jesse R. Castro
Parameters
pRedPin An int value with the address of the red leg of the LED.
pGreenPin An int value with the address of the green leg of the LED.
pBluePin An int value with the address of the blue leg of the LED.
pAutoSend A boolean value representing whether to automatically send the RGB values to the physical LED when private method setRGB is called.
pAnode A boolean value representing whether the LED is common anode or cathode
Definition at line 16 of file LEDHSV.cpp.
References init().
LEDHSV::~LEDHSV ()
Class destructor for destroying the class when it falls out of scope. This method currently doesn't do anything.
Author
Jesse R. Castro
Definition at line 19 of file LEDHSV.cpp.
Member Function Documentation
bool LEDHSV::getAnode ()
Getter method for internal variable anode.
Author
Jesse R. Castro
Returns
The value of internal private variable anode, which represents whether the LED is common cathode or anode.
Definition at line 147 of file LEDHSV.cpp.
References anode.
bool LEDHSV::getAutoSend ()
Getter method for internal variable autoSend.
Author
Jesse R. Castro
Returns
The value of internal private variable AutoSend, which represents whether to automatically send the RGB values to the physical LED when private method setRGB is called.
Definition at line 141 of file LEDHSV.cpp.
References autoSend.
int LEDHSV::getBluePin ()
Getter method for internal variable bluePin.
Author
Jesse R. Castro
Returns
The value of internal private variable BluePin, which represents pin address of the blue leg of the LED.
Definition at line 120 of file LEDHSV.cpp.
References bluePin.
int LEDHSV::getBlueValue ()
Getter method for internal variable blueValue.
Author
Jesse R. Castro
Returns
The value of internal private variable BlueValue, which represents the value to send to the blue leg of the LED from 0-255.
Definition at line 129 of file LEDHSV.cpp.
References blueValue.
float LEDHSV::getBrightness ()
Getter method for internal variable brightness.
Author
Jesse R. Castro
Returns
The value of internal private variable Brightness, which represents the brightness of the LED from 0-1.
Definition at line 138 of file LEDHSV.cpp.
References brightness.
int LEDHSV::getGreenPin ()
Getter method for internal variable greenPin.
Author
Jesse R. Castro
Returns
The value of internal private variable GreenPin, which represents pin address of the green leg of the LED.
Definition at line 117 of file LEDHSV.cpp.
References greenPin.
int LEDHSV::getGreenValue ()
Getter method for internal variable greenValue.
Author
Jesse R. Castro
Returns
The value of internal private variable GreenValue, which represents the value to send to the green leg of the LED from 0-255.
Definition at line 126 of file LEDHSV.cpp.
References greenValue.
float LEDHSV::getHue ()
Getter method for internal variable hue.
Author
Jesse R. Castro
Returns
The value of internal private variable Hue, which represents the hue of the LED from 0-1.
Definition at line 132 of file LEDHSV.cpp.
References hue.
int LEDHSV::getRedPin ()
Getter method for internal variable redPin.
Author
Jesse R. Castro
Returns
The value of internal private variable RedPin, which represents pin address of the red leg of the LED.
Definition at line 114 of file LEDHSV.cpp.
References redPin.
int LEDHSV::getRedValue ()
Getter method for internal variable redValue.
Author
Jesse R. Castro
Returns
The value of internal private variable RedValue, which represents the value to send to the red leg of the LED from 0-255.
Definition at line 123 of file LEDHSV.cpp.
References redValue.
float LEDHSV::getSaturation ()
Getter method for internal variable saturation.
Author
Jesse R. Castro
Returns
The value of internal private variable Saturation, which represents the saturation of the LED from 0-1.
Definition at line 135 of file LEDHSV.cpp.
References saturation.
bool LEDHSV::getState ()
Getter method for internal variable state.
Author
Jesse R. Castro
Returns
The value of internal private variable State, which represents whether the led is on or not.
Definition at line 144 of file LEDHSV.cpp.
References state.
void LEDHSV::HSV2RGB () protected
Converts HSV values to RGB colorspace, which is used by RGB LEDs
Author
Jesse R. Castro
Definition at line 215 of file LEDHSV.cpp.
References brightness, hue, saturation, and setRGB().
Referenced by on(), setBrightness(), setHue(), and setSaturation().
void LEDHSV::init (int pRedPin, int pGreenPin, int pBluePin, float pHue, float pSaturation, float pBrightness, bool pAutoSend, bool pAnode) protected
Initialization method to cut down on constructor copy-pasta.
Author
Jesse R. Castro
Parameters
pRedPin An int value with the address of the red leg of the LED.
pGreenPin An int value with the address of the green leg of the LED.
pBluePin An int value with the address of the blue leg of the LED.
pHue A float value representing the color of the LED.
pSaturation A float value representing the Saturation of the color of the LED.
pBrightness A float value representing the brightness of the LED.
pAutoSend A boolean value representing whether to automatically send the RGB values to the physical LED when private method setRGB is called.
pAnode A boolean value representing whether the led is common anode or cathode
Definition at line 22 of file LEDHSV.cpp.
References setAnode(), setAutoSend(), setAutoSend(), setHSV(), setPins(), setState(), and setup().
Referenced by LEDHSV(), LEDHSV(), and LEDHSV().
void LEDHSV::off ()
Turn the led off without losing the current HSV values
Author
Jesse R. Castro
Definition at line 155 of file LEDHSV.cpp.
References setRGB(), and setState().
void LEDHSV::on ()
Turn the led on with current values
Author
Jesse R. Castro
Definition at line 159 of file LEDHSV.cpp.
References HSV2RGB(), and setState().
bool LEDHSV::operator!= (const LEDHSV & pLEDHSV) const
Comparison != operator overload.
Author
Jesse R. Castro
Parameters
pLEDHSV An instance of the same type as this object.
Returns
A bool value describing the inverse of whether the objects are equivalent or not.
Definition at line 273 of file LEDHSV.cpp.
LEDHSV & LEDHSV::operator= (const LEDHSV & pLEDHSV)
Assignment operator overload.
Author
Jesse R. Castro
Parameters
pLEDHSV An instance of the same type as this object.
Returns
This object (after it has been duplicated to the pLEDHSV parameter).
Definition at line 239 of file LEDHSV.cpp.
References anode, anode, autoSend, autoSend, bluePin, bluePin, blueValue, blueValue, brightness, brightness, greenPin, greenPin, greenValue, greenValue, hue, hue, redPin, redPin, redValue, redValue, saturation, saturation, state, and state.
bool LEDHSV::operator== (const LEDHSV & pLEDHSV) const
Comparison == operator overload. Compares all values EXCEPT the pin values.
Author
Jesse R. Castro
Parameters
pLEDHSV An instance of the same type as this object.
Returns
A bool value describing whether the objects are equivalent or not.
Definition at line 256 of file LEDHSV.cpp.
References anode, anode, autoSend, autoSend, blueValue, blueValue, brightness, brightness, greenValue, greenValue, hue, hue, redValue, redValue, saturation, saturation, state, and state.
void LEDHSV::send () virtual
Sends the actual value to the RGB pins. This is a virtual function so users can redefine functionality if they want extend the class. Default functionality is to just send to pin values.
Author
Jesse R. Castro
Definition at line 163 of file LEDHSV.cpp.
References bluePin, bluePin, blueValue, blueValue, greenPin, greenPin, greenValue, greenValue, redPin, redPin, redValue, redValue, setState(), and setState().
Referenced by setRGB().
void LEDHSV::setAnode (bool pAnode) protected
Setter method for internal variable anode.
Author
Jesse R. Castro
Parameters
pState A bool value to set internal private variable Anode, which represents whether the LED is common anode
Definition at line 111 of file LEDHSV.cpp.
References anode.
Referenced by init().
void LEDHSV::setAutoSend (bool pAutoSend)
Setter method for internal variable autoSend.
Author
Jesse R. Castro
Parameters
pAutoSend A bool value to set internal private variable AutoSend, which represents whether to automatically send the RGB values to the physical LED when private method setRGB is called.
Definition at line 105 of file LEDHSV.cpp.
References autoSend.
Referenced by init(), and init().
void LEDHSV::setBluePin (int pBluePin) protected
Setter method for internal variable bluePin.
Author
Jesse R. Castro
Parameters
pBluePin An int value to set internal private variable BluePin, which represents pin address of the blue leg of the LED.
Definition at line 39 of file LEDHSV.cpp.
References bluePin.
Referenced by setPins().
void LEDHSV::setBlueValue (int pBlueValue) protected
Setter method for internal variable blueValue.
Author
Jesse R. Castro
Parameters
pBlueValue An int value to set internal private variable BlueValue, which represents the value to send to the blue leg of the LED from 0-255.
Definition at line 60 of file LEDHSV.cpp.
References blueValue, blueValue, and blueValue.
Referenced by setRGB(), and setRGB().
void LEDHSV::setBrightness (float pBrightness, bool sendAfter = true)
Setter method for internal variable brightness.
Author
Jesse R. Castro
Parameters
pBrightness A float value to set internal private variable Brightness, which represents the brightness of the LED from 0-1.
pSetAfter A boolean value that determines whether to set the RGB values after. Defaults to true.
Definition at line 93 of file LEDHSV.cpp.
References brightness, brightness, and HSV2RGB().
Referenced by setHSV().
void LEDHSV::setGreenPin (int pGreenPin) protected
Setter method for internal variable greenPin.
Author
Jesse R. Castro
Parameters
pGreenPin An int value to set internal private variable GreenPin, which represents pin address of the green leg of the LED.
Definition at line 36 of file LEDHSV.cpp.
References greenPin.
Referenced by setPins().
void LEDHSV::setGreenValue (int pGreenValue) protected
Setter method for internal variable greenValue.
Author
Jesse R. Castro
Parameters
pGreenValue An int value to set internal private variable GreenValue, which represents the value to send to the green leg of the LED from 0-255.
Definition at line 51 of file LEDHSV.cpp.
References greenValue, greenValue, and greenValue.
Referenced by setRGB(), and setRGB().
void LEDHSV::setHSV (float pHue, float pSaturation, float pBrightness)
set all three HSV values at once
Author
Jesse R. Castro
Parameters
pHue A float value to set internal private variable Hue, which represents the color of the LED from 0-1.
pSaturation A float value to set internal private variable Saturation, which represents the saturation of the color of the LED from 0-1.
pBrightness A float value to set internal private variable Brightness, which represents the brightness of the LED from 0-1.
Definition at line 196 of file LEDHSV.cpp.
References setBrightness(), setHue(), and setSaturation().
Referenced by init().
void LEDHSV::setHue (float pHue, bool sendAfter = true)
Setter method for internal variable hue.
Author
Jesse R. Castro
Parameters
pHue A float value to set internal private variable Hue, which represents the hue of the LED from 0-1.
pSetAfter A boolean value that determines whether to set the RGB values after. Defaults to true.
Definition at line 69 of file LEDHSV.cpp.
References HSV2RGB(), hue, and hue.
Referenced by setHSV().
void LEDHSV::setPins (int pRedPin, int pGreenPin, int pBluePin) protected
set all three LED pins at once
Author
Jesse R. Castro
Parameters
pRedPin An integer value to set internal variable redPin, which represents the red leg of the LED
pGreenPin An integer value to set internal variable greenPin, which represents the green leg of the LED
pBluePin An integer value to set internal variable bluePin, which represents the green leg of the LED
Definition at line 150 of file LEDHSV.cpp.
References setBluePin(), setGreenPin(), and setRedPin().
Referenced by init().
void LEDHSV::setRedPin (int pRedPin) protected
Setter method for internal variable redPin.
Author
Jesse R. Castro
Parameters
pRedPin An int value to set internal private variable RedPin, which represents pin address of the red leg of the LED.
Definition at line 33 of file LEDHSV.cpp.
References redPin.
Referenced by setPins().
void LEDHSV::setRedValue (int pRedValue) protected
Setter method for internal variable redValue.
Author
Jesse R. Castro
Parameters
pRedValue An int value to set internal private variable RedValue, which represents the value to send to the red leg of the LED from 0-255.
Definition at line 42 of file LEDHSV.cpp.
References redValue, redValue, and redValue.
Referenced by setRGB(), and setRGB().
void LEDHSV::setRGB (int pRedValue, int pGreenValue, int pBlueValue) protected
set all three RGB values at once
Author
Jesse R. Castro
Parameters
pRed A float value to set internal private variable Hue, which represents the color of the LED from 0-1.
pGreen A float value to set internal private variable Saturation, which represents the saturation of the color of the LED from 0-1.
pBlue A float value to set internal private variable Brightness, which represents the brightness of the LED from 0-1.
Definition at line 201 of file LEDHSV.cpp.
References anode, autoSend, send(), setBlueValue(), setBlueValue(), setGreenValue(), setGreenValue(), setRedValue(), and setRedValue().
Referenced by HSV2RGB(), and off().
void LEDHSV::setSaturation (float pSaturation, bool sendAfter = true)
Setter method for internal variable saturation.
Author
Jesse R. Castro
Parameters
pSaturation A float value to set internal private variable Saturation, which represents the saturation of the LED from 0-1.
pSetAfter A boolean value that determines whether to set the RGB values after. Defaults to true.
Definition at line 81 of file LEDHSV.cpp.
References HSV2RGB(), saturation, and saturation.
Referenced by setHSV().
void LEDHSV::setState (bool pState) protected
Setter method for internal variable state.
Author
Jesse R. Castro
Parameters
pState A bool value to set internal private variable State, which represents whether the led is on or off
Definition at line 108 of file LEDHSV.cpp.
References state.
Referenced by init(), off(), on(), send(), and send().
void LEDHSV::setup () protected
performs setup functions in place of the setup() routine in an arduino sketch
Author
Jesse R. Castro
Definition at line 185 of file LEDHSV.cpp.
References bluePin, bluePin, greenPin, greenPin, redPin, and redPin.
Referenced by init().
Member Data Documentation
bool LEDHSV::anode protected
whether or not the LED is common anode, determines values
Definition at line 249 of file LEDHSV.h.
Referenced by getAnode(), operator=(), operator=(), operator==(), operator==(), setAnode(), and setRGB().
bool LEDHSV::autoSend protected
whether or not to automatically send values to the LED when calling internal function setRGB
Definition at line 241 of file LEDHSV.h.
Referenced by getAutoSend(), operator=(), operator=(), operator==(), operator==(), setAutoSend(), and setRGB().
int LEDHSV::bluePin protected
pin address of the blue leg of the LED
Definition at line 213 of file LEDHSV.h.
Referenced by getBluePin(), operator=(), operator=(), send(), send(), setBluePin(), setup(), and setup().
int LEDHSV::blueValue protected
the value to send to the blue leg of the LED from 0-255
Definition at line 225 of file LEDHSV.h.
Referenced by getBlueValue(), operator=(), operator=(), operator==(), operator==(), send(), send(), setBlueValue(), setBlueValue(), and setBlueValue().
float LEDHSV::brightness protected
the brightness of the LED from 0-1
Definition at line 237 of file LEDHSV.h.
Referenced by getBrightness(), HSV2RGB(), operator=(), operator=(), operator==(), operator==(), setBrightness(), and setBrightness().
int LEDHSV::greenPin protected
pin address of the green leg of the LED
Definition at line 209 of file LEDHSV.h.
Referenced by getGreenPin(), operator=(), operator=(), send(), send(), setGreenPin(), setup(), and setup().
int LEDHSV::greenValue protected
the value to send to the green leg of the LED from 0-255
Definition at line 221 of file LEDHSV.h.
Referenced by getGreenValue(), operator=(), operator=(), operator==(), operator==(), send(), send(), setGreenValue(), setGreenValue(), and setGreenValue().
float LEDHSV::hue protected
the hue of the LED from 0-1
Definition at line 229 of file LEDHSV.h.
Referenced by getHue(), HSV2RGB(), operator=(), operator=(), operator==(), operator==(), setHue(), and setHue().
int LEDHSV::redPin protected
pin address of the red leg of the LED
Definition at line 205 of file LEDHSV.h.
Referenced by getRedPin(), operator=(), operator=(), send(), send(), setRedPin(), setup(), and setup().
int LEDHSV::redValue protected
the value to send to the red leg of the LED from 0-255
Definition at line 217 of file LEDHSV.h.
Referenced by getRedValue(), operator=(), operator=(), operator==(), operator==(), send(), send(), setRedValue(), setRedValue(), and setRedValue().
float LEDHSV::saturation protected
the saturation of the LED from 0-1
Definition at line 233 of file LEDHSV.h.
Referenced by getSaturation(), HSV2RGB(), operator=(), operator=(), operator==(), operator==(), setSaturation(), and setSaturation().
bool LEDHSV::state protected
whether or not the led is on
Definition at line 245 of file LEDHSV.h.
Referenced by getState(), operator=(), operator=(), operator==(), operator==(), and setState().
The documentation for this class was generated from the following files:
LEDHSV.h
LEDHSV.cpp